/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) ٢٠٢٦ STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>
typedef volatile uint32_t vuint32_t;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define RCC  0x40021000
#define GPIO_PA  0x40010800
#define APB2ENR   *(vuint32_t *)(RCC + 0x18)
#define CRH       *(vuint32_t *)(GPIO_PA + 0x04)
typedef union {
	vuint32_t allfeilds;
	struct {
		vuint32_t reseved :13;
		vuint32_t p13 :1;
	} Pin;
} S_ODR_t;
int main(void) {
	APB2ENR |= 1 << 2;
	CRH &= 0xff0fffff;
	CRH |= 0x00200000;
	volatile S_ODR_t *ODR = (S_ODR_t*) (GPIO_PA + 0x0C);
	while (1) {
		ODR->Pin.p13 = 1;
		for (int i = 1; i < 5000; i++)
			;
		ODR->Pin.p13 = 0;
		for (int i = 1; i < 5000; i++)
			;

	}
}
